default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: Jakub
  password: hodi2007

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: jh_project_production